Cargo.toml
examples/bevy_video.rs

Testing has reached its working state, this will bring the tests to the dev branch for refactoring into the correct format within the main merge afterwards

Merge Testing branch

---

.gitignore
Cargo.toml
README.md
camera_controls.txt
examples/camera_setting.rs
src/components.rs
src/lib.rs
src/plugin.rs
src/systems.rs

Pull and merge of the new things to the old dev branch so that they can be efficiently combined

Update the dev branch before full merge

---

Cargo.toml
examples/bevy_bluetooth.rs
examples/bevy_video.rs
examples/bluetooth.rs
src/bluetooth.rs
src/lib.rs

Updated the bluetooth stuff so that the inputs can be read from the arduino.
Next is to refactor and clean up the `src` files for a better integration with the soon-to-be-coming audio and GUI modules.

Combine the new things from dev into main

---

examples/gui_test.rs
src/gui.rs
src/lib.rs

First step to remove christians old branches and pull them into main.

Quick combining of Christians 2 branches

---

Cargo.toml
examples/audio.rs

created an example of the audio playback system and update the .toml to reflect the requirements of the new dependency.

Create the groundwork for how the audio systems will be done

---

examples/gui_test.rs
examples/uhdrtz.rs
src/bluetooth.rs
src/gui.rs
src/lib.rs
src/plugin.rs
src/zoetrope.rs

Allows the integration with the Plugins system that was created.

Merge the cleanup changes to the audio branch

---

examples/gui_test.rs
src/gui.rs
src/lib.rs

Update to main for the gui layouts for camera controls to come in the next few updates.

Update the gui for camera controls and coloration

---

Cargo.toml
src/plugin.rs

Removed it without thinking about how its used on the primary device

Bring back the embedded assets plugin

---

src/gui.rs

I changed zoom so it works again

added zoom back in

---

src/gui.rs
src/plugin.rs
src/setup.rs
src/zoetrope.rs

This update allows for the animation to cap at 24 fps.

Fix the animation for 24fps

---

src/audio.rs
src/gui.rs
src/lib.rs
src/plugin.rs
src/zoetrope.rs

There was a ton of dead code from the removal of the masking system, as well as the fixing of the different systems for other uses. This shrinks the codebase by a large factor.

Cleanup a lot of dead and removed code from the userbase

---

src/gui.rs

Created a UI element in the runtime section that allows changing the required rotational speed of the crank in which the zoetrope fully animates.

Create a threshold changer

---

src/gui.rs
src/plugin.rs
src/setup.rs
src/zoetrope.rs

Changes the setup menu and some inner workings to allow for more control over the configuration of the whole system.

Allow changes to the animation slices

---

src/camera.rs
src/gui.rs
src/plugin.rs
src/setup.rs
src/zoetrope.rs

A bunch of commits that allow movement of the disk to the corners or the bottom of the screen.

Create buttons for moving the disk

---

src/camera.rs
src/gui.rs
src/zoetrope.rs

This uses the new defaulting system from the commit before this.

Move around some code, add in functionality to reset the camera controls

---

src/setup.rs

Only start up the system when both a camera and an arduino are ready

Update the button to switch states only on camera and arduino connections

---

src/audio.rs
src/gui.rs
src/plugin.rs
src/zoetrope.rs

Created a UI element that changes the direction of the audio or the animation

---

src/gui.rs

This affects the case when the semi circle location is used.

Change the size of the circle

---

src/audio.rs
src/gui.rs
src/lib.rs
src/plugin.rs

Kind of a messy commit that slightly changes how the volume is changed. It should limit the amount of errors in the log now.

Change to some event handling instead of resources

---

runner

Second commit that adds in the file for running the system.

Add a runner script

---

src/audio.rs
src/gui.rs
src/plugin.rs
src/setup.rs

Add in things that address the following issues.

Add in some small QOL changes
